"""
Tests for your Drafter website.
"""

from drafter import *
from bakery import assert_equal

# do_not_start_server(): Prevent the server from starting during tests
get_main_server().configuration.skip = True

from main import *

## You can add your tests below this line

assert_equal(
 index(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[])),
 Page(state=State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[]),
     content=[Header(body='Course Tracker', level=1),
              'Enter a Course:',
              TextBox(name='course_name', kind='text', default_value=''),
              Button(text='Save Course', url='/save_course'),
              Button(text='To Courses!', url='/courses_list')]))

assert_equal(
 add_assignments(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Physics'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=['Enter Assignment Name:',
              TextBox(name='assignment_name', kind='text', default_value=''),
              'Enter Assignment Description:',
              TextBox(name='assignment_desc', kind='text', default_value=''),
              'Enter Progress (Not Started, In Progress, or Done):',
              TextBox(name='assignment_progress', kind='text', default_value=''),
              'Enter Assignment Grade:',
              TextBox(name='assignment_grade', kind='text', default_value='0.0'),
              'Save Assignment Data:',
              Button(text='Save', url='/save_assignment', arguments=Argument(name='course', value='Physics'))]))

assert_equal(
 save_assignment(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Physics', 'Homework 1', '-', 'Done', '90.0'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=90.0)],
                                 course_grade=90.0)]),
     content=[Header(body='Physics', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Homework 1 | Description: - | Progress: Done | Grade: 90.0%'], kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='90.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Physics')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 courses_list(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[], course_grade=0.0), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)])),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math', assignment_list=[], course_grade=0.0),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Courses List', level=3),
              Button(text='Math', url='/course_page', arguments=Argument(name='course', value='Math')),
              Button(text='English', url='/course_page', arguments=Argument(name='course', value='English')),
              Button(text='Physics', url='/course_page', arguments=Argument(name='course', value='Physics')),
              Button(text='Add Another Course', url='/')]))

assert_equal(
 course_page(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[Assignment(name='Homework 1', description='-', progress='Done', assignment_grade=90.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=82.5)]), 'Math'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=90.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=82.5)]),
     content=[Header(body='Math', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Homework 1 | Description: - | Progress: Not Started  | Grade: 100.0%',
                                  'Name: Homework 2 | Description: - | Progress: In Progress | Grade: 75.0%'],
                           kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='87.5%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Math')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 course_page(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'English'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='English', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=[], kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='0.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='English')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 save_assignment(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[Assignment(name='Homework 1', description='-', progress='Done', assignment_grade=90.0)], course_grade=90.0)]), 'Physics', 'Homework 2', '-', 'In Progress', '75.0'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=90.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=82.5)]),
     content=[Header(body='Physics', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Homework 1 | Description: - | Progress: Done | Grade: 90.0%',
                                  'Name: Homework 2 | Description: - | Progress: In Progress | Grade: 75.0%'],
                           kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='82.5%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Physics')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 course_page(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[Assignment(name='Homework 1', description='-', progress='Done', assignment_grade=90.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=82.5)]), 'English'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=90.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=82.5)]),
     content=[Header(body='English', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Essay | Description: - | Progress: Done | Grade: 95.0%',
                                  'Name: Discussion Post | Description: - | Progress: In Progress | Grade: 85.0%'],
                           kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='90.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='English')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 save_assignment(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[], course_grade=0.0), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Math', 'Homework 1', '-', 'Not Started ', '100.0'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0)],
                                 course_grade=100.0),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Math', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Homework 1 | Description: - | Progress: Not Started  | Grade: 100.0%'],
                           kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='100.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Math')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 save_course(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[], course_grade=0.0), Course(name='English', assignment_list=[], course_grade=0.0)]), 'Physics'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math', assignment_list=[], course_grade=0.0),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Course Tracker', level=1),
              'Enter a Course:',
              TextBox(name='course_name', kind='text', default_value=''),
              Button(text='Save Course', url='/save_course'),
              Button(text='To Courses!', url='/courses_list')]))

assert_equal(
 courses_list(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[Assignment(name='Homework 1', description='-', progress='Done', assignment_grade=90.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=82.5)])),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=90.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=82.5)]),
     content=[Header(body='Courses List', level=3),
              Button(text='Math', url='/course_page', arguments=Argument(name='course', value='Math')),
              Button(text='English', url='/course_page', arguments=Argument(name='course', value='English')),
              Button(text='Physics', url='/course_page', arguments=Argument(name='course', value='Physics')),
              Button(text='Add Another Course', url='/')]))

assert_equal(
 add_assignments(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'English'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=['Enter Assignment Name:',
              TextBox(name='assignment_name', kind='text', default_value=''),
              'Enter Assignment Description:',
              TextBox(name='assignment_desc', kind='text', default_value=''),
              'Enter Progress (Not Started, In Progress, or Done):',
              TextBox(name='assignment_progress', kind='text', default_value=''),
              'Enter Assignment Grade:',
              TextBox(name='assignment_grade', kind='text', default_value='0.0'),
              'Save Assignment Data:',
              Button(text='Save', url='/save_assignment', arguments=Argument(name='course', value='English'))]))

assert_equal(
 save_course(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[]), 'Math'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Course Tracker', level=1),
              'Enter a Course:',
              TextBox(name='course_name', kind='text', default_value=''),
              Button(text='Save Course', url='/save_course'),
              Button(text='To Courses!', url='/courses_list')]))

assert_equal(
 save_assignment(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'English', 'Essay', '-', 'Done', '95.0'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0)],
                                 course_grade=95.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='English', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Essay | Description: - | Progress: Done | Grade: 95.0%'], kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='95.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='English')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 add_assignments(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[], course_grade=0.0), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Math'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math', assignment_list=[], course_grade=0.0),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=['Enter Assignment Name:',
              TextBox(name='assignment_name', kind='text', default_value=''),
              'Enter Assignment Description:',
              TextBox(name='assignment_desc', kind='text', default_value=''),
              'Enter Progress (Not Started, In Progress, or Done):',
              TextBox(name='assignment_progress', kind='text', default_value=''),
              'Enter Assignment Grade:',
              TextBox(name='assignment_grade', kind='text', default_value='0.0'),
              'Save Assignment Data:',
              Button(text='Save', url='/save_assignment', arguments=Argument(name='course', value='Math'))]))

assert_equal(
 course_page(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Physics'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Physics', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=[], kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='0.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Physics')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 course_page(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[], course_grade=0.0), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Math'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math', assignment_list=[], course_grade=0.0),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Math', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=[], kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='0.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Math')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 save_course(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[], course_grade=0.0)]), 'English'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math', assignment_list=[], course_grade=0.0),
                          Course(name='English', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Course Tracker', level=1),
              'Enter a Course:',
              TextBox(name='course_name', kind='text', default_value=''),
              Button(text='Save Course', url='/save_course'),
              Button(text='To Courses!', url='/courses_list')]))

assert_equal(
 add_assignments(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0)], course_grade=100.0), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Math'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0)],
                                 course_grade=100.0),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=['Enter Assignment Name:',
              TextBox(name='assignment_name', kind='text', default_value=''),
              'Enter Assignment Description:',
              TextBox(name='assignment_desc', kind='text', default_value=''),
              'Enter Progress (Not Started, In Progress, or Done):',
              TextBox(name='assignment_progress', kind='text', default_value=''),
              'Enter Assignment Grade:',
              TextBox(name='assignment_grade', kind='text', default_value='0.0'),
              'Save Assignment Data:',
              Button(text='Save', url='/save_assignment', arguments=Argument(name='course', value='Math'))]))

assert_equal(
 add_assignments(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0)], course_grade=95.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'English'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0)],
                                 course_grade=95.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=['Enter Assignment Name:',
              TextBox(name='assignment_name', kind='text', default_value=''),
              'Enter Assignment Description:',
              TextBox(name='assignment_desc', kind='text', default_value=''),
              'Enter Progress (Not Started, In Progress, or Done):',
              TextBox(name='assignment_progress', kind='text', default_value=''),
              'Enter Assignment Grade:',
              TextBox(name='assignment_grade', kind='text', default_value='0.0'),
              'Save Assignment Data:',
              Button(text='Save', url='/save_assignment', arguments=Argument(name='course', value='English'))]))

assert_equal(
 courses_list(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[], course_grade=0.0)])),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Courses List', level=3),
              Button(text='Math', url='/course_page', arguments=Argument(name='course', value='Math')),
              Button(text='English', url='/course_page', arguments=Argument(name='course', value='English')),
              Button(text='Physics', url='/course_page', arguments=Argument(name='course', value='Physics')),
              Button(text='Add Another Course', url='/')]))

assert_equal(
 save_assignment(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0)], course_grade=95.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'English', 'Discussion Post', '-', 'In Progress', '85.0'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='English', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Essay | Description: - | Progress: Done | Grade: 95.0%',
                                  'Name: Discussion Post | Description: - | Progress: In Progress | Grade: 85.0%'],
                           kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='90.0%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='English')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 save_assignment(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0)], course_grade=100.0), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)]), 'Math', 'Homework 2', '-', 'In Progress', '75.0'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Math', level=1),
              Header(body='Assignments:', level=5),
              NumberedList(items=['Name: Homework 1 | Description: - | Progress: Not Started  | Grade: 100.0%',
                                  'Name: Homework 2 | Description: - | Progress: In Progress | Grade: 75.0%'],
                           kind='ol'),
              Header(body='Grade:', level=5),
              Header(body='87.5%', level=6),
              Button(text='Add Assignments', url='/add_assignments', arguments=Argument(name='course', value='Math')),
              Button(text='Return', url='/courses_list')]))

assert_equal(
 courses_list(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[], course_grade=0.0), Course(name='Physics', assignment_list=[], course_grade=0.0)])),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English', assignment_list=[], course_grade=0.0),
                          Course(name='Physics', assignment_list=[], course_grade=0.0)]),
     content=[Header(body='Courses List', level=3),
              Button(text='Math', url='/course_page', arguments=Argument(name='course', value='Math')),
              Button(text='English', url='/course_page', arguments=Argument(name='course', value='English')),
              Button(text='Physics', url='/course_page', arguments=Argument(name='course', value='Physics')),
              Button(text='Add Another Course', url='/')]))

assert_equal(
 add_assignments(State(user_name='', current_course=Course(name='', assignment_list=[], course_grade=0.0), courses=[Course(name='Math', assignment_list=[Assignment(name='Homework 1', description='-', progress='Not Started ', assignment_grade=100.0), Assignment(name='Homework 2', description='-', progress='In Progress', assignment_grade=75.0)], course_grade=87.5), Course(name='English', assignment_list=[Assignment(name='Essay', description='-', progress='Done', assignment_grade=95.0), Assignment(name='Discussion Post', description='-', progress='In Progress', assignment_grade=85.0)], course_grade=90.0), Course(name='Physics', assignment_list=[Assignment(name='Homework 1', description='-', progress='Done', assignment_grade=90.0)], course_grade=90.0)]), 'Physics'),
 Page(state=State(user_name='',
                 current_course=Course(name='', assignment_list=[], course_grade=0.0),
                 courses=[Course(name='Math',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Not Started ',
                                                             assignment_grade=100.0),
                                                  Assignment(name='Homework 2',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=75.0)],
                                 course_grade=87.5),
                          Course(name='English',
                                 assignment_list=[Assignment(name='Essay',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=95.0),
                                                  Assignment(name='Discussion Post',
                                                             description='-',
                                                             progress='In Progress',
                                                             assignment_grade=85.0)],
                                 course_grade=90.0),
                          Course(name='Physics',
                                 assignment_list=[Assignment(name='Homework 1',
                                                             description='-',
                                                             progress='Done',
                                                             assignment_grade=90.0)],
                                 course_grade=90.0)]),
     content=['Enter Assignment Name:',
              TextBox(name='assignment_name', kind='text', default_value=''),
              'Enter Assignment Description:',
              TextBox(name='assignment_desc', kind='text', default_value=''),
              'Enter Progress (Not Started, In Progress, or Done):',
              TextBox(name='assignment_progress', kind='text', default_value=''),
              'Enter Assignment Grade:',
              TextBox(name='assignment_grade', kind='text', default_value='0.0'),
              'Save Assignment Data:',
              Button(text='Save', url='/save_assignment', arguments=Argument(name='course', value='Physics'))]))
